FROM ubuntu
WORKDIR /app
RUN apt update
RUN apt install -y nodejs
RUN apt install -y npm
RUN apt install -y wget
RUN npm install -g n
RUN n latest
COPY ./upload_service/ .
RUN npm install -g yarn
RUN yarn install
CMD [ "node", "./index.js" ]